// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuxSUtIERIrfOqHj1UYcysYzTmISrsT-Y',
    appId: '1:858179757629:android:eac383b9ac6da2db3e6c54',
    messagingSenderId: '858179757629',
    projectId: 'whatsapp-clone-9ddb8',
    storageBucket: 'whatsapp-clone-9ddb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPrFNTPiNXzFeVtQHUMTTT8jXGdHhHfZM',
    appId: '1:858179757629:ios:d6a97e54047d64e43e6c54',
    messagingSenderId: '858179757629',
    projectId: 'whatsapp-clone-9ddb8',
    storageBucket: 'whatsapp-clone-9ddb8.appspot.com',
    iosClientId: '858179757629-nd1u7tf0g9o7a5f2gg7393o1kor1lmvi.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
